import { useState } from "react";
import { Play, Square } from "lucide-react";
import { Card, DisabledAction, EmptyTable, LocalTabs, Metric, Unavailable, inputClass } from "./primitives";

const presets = [{ label: "Top 3", description: "Fastest approved shortlist" }, { label: "Top 5", description: "Balanced deployment basket" }, { label: "Approved", description: "All approved configs" }, { label: "Custom", description: "Comma-separated symbol list" }];

// Adapted from AlertSetupWorkspace.tsx at cc740a1; form state stays in memory only.
export function AlertSetupPage() {
  const [preset, setPreset] = useState<string | null>(null);
  const [timeframe, setTimeframe] = useState("");
  const [name, setName] = useState("");
  const [webhook, setWebhook] = useState("");
  const [pairs, setPairs] = useState("");
  const [tab, setTab] = useState("Results");
  return <div className="space-y-4 animate-fade-in-up"><header className="flex items-start justify-between gap-3"><div><h1 className="page-title text-lg font-semibold">Alert Setup</h1><p className="page-subtitle mt-0.5 text-xs">Deploy approved pair configs into TradingView alerts and track batch progress.</p></div><span className="tf-badge">OPS</span></header><Unavailable>alert runner, approved configurations, and batch services are not connected. Form changes are unsaved local drafts.</Unavailable>
    <Card title="Alert Setup runner" description="Deploy approved pair configs into TradingView alerts one batch at a time." accessory={<span className="text-xs text-[var(--to-text-dim)]">Runner unavailable</span>}><div className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><fieldset className="space-y-1 text-xs text-[var(--to-text-secondary)] md:col-span-2 xl:col-span-3"><legend>Preset</legend><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{presets.map((option) => <button key={option.label} type="button" aria-pressed={preset === option.label} onClick={() => setPreset(option.label)} className={`rounded-lg border px-3 py-2 text-left transition-colors ${preset === option.label ? "border-[var(--to-accent-amber)] bg-[var(--to-accent-amber)]/10" : "border-[var(--to-border)] hover:bg-[var(--to-surface-raised)]/50"}`}><span className="block text-sm font-medium text-[var(--to-text-primary)]">{option.label}</span><span className="mt-0.5 block text-[10px] text-[var(--to-text-dim)]">{option.description}</span></button>)}</div></fieldset><label className="space-y-1 text-xs text-[var(--to-text-secondary)]"><span>Timeframe</span><select value={timeframe} onChange={(event) => setTimeframe(event.target.value)} className={inputClass}><option value="">Select local draft</option>{["1m", "5m", "15m", "1h"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="space-y-1 text-xs text-[var(--to-text-secondary)]"><span>Alert name prefix</span><input aria-label="Alert name" value={name} onChange={(event) => setName(event.target.value)} className={inputClass} /></label><label className="space-y-1 text-xs text-[var(--to-text-secondary)]"><span>Webhook URL</span><input value={webhook} onChange={(event) => setWebhook(event.target.value)} placeholder="Local draft only" className={inputClass} /></label><div className="text-xs text-[var(--to-text-secondary)] md:col-span-2 xl:col-span-3">Use approved risk weights <span className="text-[10px] text-[var(--to-text-dim)]">— Unavailable; source weights are not connected.</span></div></div>
      {preset === "Custom" && <label className="block space-y-1 text-xs text-[var(--to-text-secondary)]"><span>Custom pairs</span><input value={pairs} onChange={(event) => setPairs(event.target.value)} className={inputClass} placeholder="Comma-separated local draft" /></label>}
      <div className="rounded-xl border border-[var(--to-border)] bg-[var(--to-surface-raised)]/40 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.18em] text-[var(--to-text-dim)]">Selected pairs</p><p className="mt-1 text-sm text-[var(--to-text-secondary)]">{preset ?? "Preset unavailable"} · pair count — · {timeframe || "timeframe —"}</p></div><span className="text-xs text-[var(--to-text-dim)]">Approved preview unavailable</span></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><p className="text-xs text-[var(--to-text-dim)]">Unavailable — approved pair configs have not been loaded.</p></div></div>
      <div className="flex flex-wrap items-start gap-2"><DisabledAction reason="Batch creation requires the disconnected alert runner."><Play className="h-4 w-4" />Start Batch</DisabledAction><DisabledAction reason="Batch cancellation is not connected."><Square className="h-4 w-4" />Cancel Batch</DisabledAction></div></div></Card>
    <Card title="Active batch" description="Latest running or selected historical alert batch."><div className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6">{["Status", "Completed pairs", "Running pairs", "Failed pairs", "Alerts created", "Batch timing"].map((label) => <Metric key={label} label={label} detail={label === "Batch timing" ? "Queued at: — · Started at: —" : undefined} />)}</div><div className="space-y-2"><div className="flex items-center justify-between text-xs text-[var(--to-text-dim)]"><span>Progress</span><span>Unavailable</span></div><div className="h-2 rounded-full bg-[var(--to-surface)]" /></div></div></Card>
    <LocalTabs label="Alert batch details" tabs={["Results", "Timeline", "History", "Approved"]} active={tab} onChange={setTab} line>{tab === "Results" ? <Card title="Results" description="Per-pair alert creation output for the selected batch."><EmptyTable label="Alert results" columns={["Pair", "Status", "Alert Name", "Risk", "Timeframe", "Alert ID", "Error"]} reason="batch results are not connected." /></Card> : tab === "Timeline" ? <Card title="Timeline" description="Machine-readable event feed and log lines."><Unavailable>batch events are not connected.</Unavailable></Card> : tab === "History" ? <Card title="History" description="Select a prior batch to inspect details."><Unavailable>batch history is not connected.</Unavailable></Card> : <Card title="Approved configs" description="Source list used for presets and alert deployment."><EmptyTable label="Approved configs" columns={["Rank", "Pair", "Timeframe", "Score", "PF", "Max DD %", "Risk", "Source Run"]} reason="approved configurations are not connected." /></Card>}</LocalTabs>
  </div>;
}
