import { useId, useState } from "react";
import { Bell, ShieldAlert, AlertTriangle, Info, Inbox, RefreshCw, CheckCircle2, Trash2 } from "lucide-react";
import { DisabledAction, Unavailable, moveLocalTabFocus } from "./primitives";

const filters = ["All", "Critical", "Error", "Warning", "Info"] as const;
const stats = [{ label: "Active Alerts", filter: "All", Icon: Bell, tone: "text-amber-400", bg: "bg-amber-500/10 border-amber-500/20" }, { label: "Critical / Error", filter: "Critical", Icon: ShieldAlert, tone: "text-rose-400", bg: "bg-rose-500/10 border-rose-500/20" }, { label: "Warnings", filter: "Warning", Icon: AlertTriangle, tone: "text-amber-400", bg: "bg-amber-500/10 border-amber-500/20" }, { label: "Info", filter: "Info", Icon: Info, tone: "text-blue-400", bg: "bg-blue-500/10 border-blue-500/20" }, { label: "Dead Letters", filter: null, Icon: Inbox, tone: "text-[var(--to-text-dim)]", bg: "bg-[var(--to-surface-raised)] border-[var(--to-border)]" }];

// Presentation adapted from frontend/src/app/alerts/page.tsx at cc740a1.
export function AlertsPage() {
  const [filter, setFilter] = useState("All");
  const tabId = useId();
  return <div className="space-y-4 animate-fade-in-up"><header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg border border-amber-500/20 bg-amber-500/10"><Bell className="h-4 w-4 text-amber-400" /></div><div><h1 className="page-title text-lg font-semibold">Alerts</h1><p className="page-subtitle mt-0.5 text-xs">Monitoring · Active alerts &amp; dead letters</p></div></div><div className="flex items-start gap-2"><DisabledAction reason="Alert service is not connected."><RefreshCw className="h-3 w-3" />Refresh</DisabledAction><DisabledAction reason="Acknowledgement writes are not connected."><CheckCircle2 className="h-3 w-3" />Acknowledge All</DisabledAction></div></header>
    <Unavailable>alert monitoring and dead-letter services are not connected. Counts are unknown.</Unavailable>
    <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">{stats.map(({ label, filter: target, Icon, tone, bg }) => <button key={label} type="button" disabled={!target} aria-pressed={target ? filter === target : undefined} onClick={() => target && setFilter(target)} className={`rounded-xl border p-4 text-left transition-all duration-150 bg-[var(--to-surface)] ${filter === target ? "border-[var(--to-warning)]/40 bg-[var(--to-warning)]/5" : "border-[var(--to-border)]"}`}><div className={`mb-2 flex h-8 w-8 items-center justify-center rounded-lg border ${bg}`}><Icon className={`h-4 w-4 ${tone}`} /></div><div className="font-mono text-2xl font-bold tabular-nums text-[var(--to-text-primary)]">—</div><div className="mt-0.5 font-mono text-[10px] font-bold uppercase tracking-widest text-[var(--to-text-dim)]">{label}</div></button>)}</div>
    <div role="tablist" aria-label="Alert severity" className="flex flex-wrap items-center gap-1.5">{filters.map((label, index) => <button key={label} type="button" role="tab" tabIndex={filter === label ? 0 : -1} id={`${tabId}-${index}`} aria-controls={`${tabId}-panel`} aria-selected={filter === label} onClick={() => setFilter(label)} onKeyDown={(event) => moveLocalTabFocus(event, filters, index, setFilter)} className={`rounded-md border px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-widest transition-all focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-400 ${filter === label ? "border-amber-500/40 bg-amber-500/10 text-amber-400" : "border-[var(--to-border)] bg-[var(--to-surface)] text-[var(--to-text-dim)]"}`}>{label}</button>)}</div>
    <section aria-label="Active alerts"><div role="tabpanel" tabIndex={0} id={`${tabId}-panel`} aria-labelledby={`${tabId}-${filters.findIndex((label) => label === filter)}`} className="rounded-xl border border-[var(--to-border)] overflow-hidden py-10 text-center space-y-1"><Info className="mx-auto h-5 w-5 text-[var(--to-text-dim)]" /><p className="font-mono text-xs text-[var(--to-text-dim)]">Unavailable — {filter === "All" ? "active" : filter.toLowerCase()} alerts cannot be read from the paper API.</p></div></section>
    <section aria-label="Dead Letters"><div className="mb-3 flex items-center justify-between"><h2 className="font-mono text-sm font-bold text-[var(--to-text-primary)]">Dead Letters</h2><DisabledAction reason="Dead-letter deletion is not connected."><Trash2 className="h-3 w-3" />Clear All</DisabledAction></div><div className="rounded-xl border border-[var(--to-border)] py-8 text-center"><Inbox className="mx-auto mb-1 h-5 w-5 text-[var(--to-text-dim)]" /><p className="font-mono text-xs text-[var(--to-text-dim)]">Unavailable — queue state is unknown; retry and discard controls require the alert service.</p></div></section>
  </div>;
}
