import { Calendar, Clock, RefreshCw, Shield, Trophy } from "lucide-react";
import { ChartUnavailable, DisabledAction, Metric, Unavailable, inputClass } from "./primitives";
import type { ReactNode } from "react";

function Section({ title, children, glass = false }: { title: string; children: ReactNode; glass?: boolean }) {
  return <section aria-label={title} className={`${glass ? "glass-panel" : "glow-card"} p-6`}><h2 className="text-[13px] font-bold text-[var(--to-text-dim)] uppercase tracking-widest font-mono mb-4">{title}</h2>{children}</section>;
}

function UnknownGauge({ label, size = 150 }: { label: string; size?: number }) {
  return <div className="flex flex-col items-center"><div className="relative"><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[32px] font-bold font-mono text-[var(--to-text-dim)]">—</div><div className="text-[11px] text-[var(--to-text-dim)] mt-1">Unavailable</div></div></div><svg role="img" aria-label={`${label} unavailable`} width={size} height={size} viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="none" stroke="var(--to-border)" strokeWidth="8" /></svg></div>{label !== "Challenge health" && <><p className="mt-2 font-mono text-xs text-[var(--to-text-secondary)]">{label}</p><p className="mt-1 text-[11px] text-[var(--to-text-dim)]">Limit: —</p></>}</div>;
}

// Page and prop-firm component presentations from cc740a1. No MOCK_METRICS fallback.
export function PropFirmPage() {
  return <div className="flex-1 space-y-4 animate-fade-in-up"><Unavailable>prop-firm accounts, challenge metrics, limits, and broker history are not connected. No demo data is shown.</Unavailable>
    <header className="glow-card p-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div className="space-y-3"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-amber-500/30 bg-amber-500/10"><Trophy className="h-6 w-6 text-amber-400" /></div><div><h1 className="text-[22px] font-black text-[var(--to-text-primary)] tracking-tight">Prop Firm Challenge</h1><div className="flex flex-wrap items-center gap-2 mt-1"><span className="text-[12px] text-[var(--to-text-dim)] font-mono">Account unavailable</span><span className="inline-flex gap-1.5 rounded-lg border border-[var(--to-border)] px-3 py-1.5 text-[11px] font-mono text-[var(--to-text-dim)]">Phase unavailable</span><span className="flex items-center gap-1 text-[11px] text-[var(--to-text-dim)] font-mono"><Clock className="h-3 w-3" />— days remaining</span></div></div></div><select aria-label="Challenge account" value="" disabled className={inputClass}><option value="">Unavailable</option></select></div><DisabledAction reason="Daily reset is a broker-service write and is not connected."><RefreshCw className="h-3.5 w-3.5" />Reset Daily</DisabledAction></div></header>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Section title="Challenge Health"><UnknownGauge label="Challenge health" size={180} /><p className="mt-4 text-center text-[13px] text-[var(--to-text-dim)]">Trading eligibility unavailable</p></Section><div className="lg:col-span-2"><Section title="Account Overview" glass><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{["Starting Balance", "Current Equity", "Daily P&L", "Floating P&L"].map((label) => <Metric key={label} label={label} />)}</div></Section></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Section title="Equity Curve" glass><ChartUnavailable label="Equity history" height="h-[240px]" /></Section><Section title="Daily P&L" glass><ChartUnavailable label="Daily performance" height="h-[240px]" /></Section></div>
    <Section title="Challenge Metrics"><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{["Daily Drawdown", "Max Drawdown", "Consistency Rule"].map((label) => <UnknownGauge key={label} label={label} />)}</div></Section>
    <Section title="Challenge Rules"><div className="space-y-2">{["Daily Loss Limit", "Max Drawdown", "Consistency Rule", "Profit Target", "Min Trading Days", "Time Limit"].map((label) => <div key={label} className="flex items-center justify-between px-3 py-2 rounded-lg border border-[#2a2e39] bg-[#1e222d]/30"><div className="flex items-center gap-2"><Shield className="h-3.5 w-3.5 text-[var(--to-text-dim)]" /><span className="font-mono text-xs text-[var(--to-text-secondary)]">{label}</span></div><span className="font-mono text-xs text-[var(--to-text-dim)]">Unavailable · limit —</span></div>)}</div></Section>
    <Section title="Payout Readiness" glass><div className="mb-4 text-right font-mono text-[11px] text-[var(--to-text-dim)]">Unavailable</div><div className="space-y-2">{["Profit Target", "Min Trading Days", "No Daily Loss Breach", "No Max Drawdown Breach", "Consistency Rule"].map((label) => <div key={label} className="flex items-center gap-3 px-3 py-2.5 rounded-lg border border-[#2a2e39] bg-[#1e222d]/20"><span className="text-[var(--to-text-dim)]">—</span><div><div className="text-xs font-mono text-[var(--to-text-secondary)]">{label}</div><div className="text-[10px] font-mono mt-0.5 text-[var(--to-text-dim)]">Unavailable</div></div></div>)}</div></Section>
    <Section title="Performance Summary"><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{["Open Positions", "Closed Trades", "Win Rate", "Total PnL", "Best / Worst Day"].map((label) => <Metric key={label} label={label} />)}</div></Section>
    <Section title="Daily Performance Calendar" glass><div className="flex items-center gap-2 mb-4"><Calendar className="h-4 w-4 text-amber-400" /><p className="text-xs font-mono text-[var(--to-text-dim)]">Calendar period unavailable</p></div><div className="grid grid-cols-7 gap-px rounded-lg border border-[var(--to-border)] overflow-hidden">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <div key={day} className="py-2 text-center text-[10px] font-mono text-[var(--to-text-dim)] bg-[var(--to-surface-raised)]">{day}</div>)}<div className="col-span-7 py-12 text-center text-xs text-[var(--to-text-dim)]">Unavailable — no connected trade history.</div></div></Section>
  </div>;
}
