import { useState } from "react";
import { Plus, Save } from "lucide-react";
import { DisabledAction, Unavailable } from "./primitives";

// Presentation adapted from frontend/src/app/strategies/page.tsx at cc740a1.
export function StrategiesPage() {
  const [configText, setConfigText] = useState("");
  return <div className="flex flex-col gap-4 h-full animate-fade-in-up md:flex-row"><aside aria-label="Strategies" className="w-full md:w-64 md:shrink-0 flex flex-col glow-card p-3 space-y-3"><div className="flex items-start justify-between gap-2"><span className="text-xs font-mono text-[var(--to-text-dim)] uppercase tracking-wider">Strategies</span><DisabledAction reason="Strategy creation is not connected."><Plus className="w-3 h-3" />New</DisabledAction></div><p className="text-xs text-[var(--to-text-dim)] font-mono">Unavailable — strategy definitions are not connected.</p></aside><div className="min-w-0 flex-1 flex flex-col glow-card p-4 space-y-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="page-title text-sm font-semibold">Strategy Studio</h1><p className="page-subtitle mt-0.5 text-[11px]">Edit strategy-as-data config (JSON) with validation.</p></div><DisabledAction reason="Strategy activation service is not connected.">Activation unavailable</DisabledAction></div><Unavailable>strategy state and server validation are not connected. The editor is an unsaved local draft only.</Unavailable><div className="flex flex-wrap items-start justify-between gap-2"><span className="text-[11px] text-[var(--to-text-secondary)] font-mono">ID — · version — · activation unavailable</span><div className="flex gap-2"><DisabledAction reason="Server validation is not connected.">Validate</DisabledAction><DisabledAction reason="Strategy writes are not connected."><Save className="w-3.5 h-3.5" />Save</DisabledAction></div></div><textarea aria-label="Strategy configuration JSON" id="strategy-config-editor" value={configText} onChange={(event) => setConfigText(event.target.value)} className="flex-1 min-h-96 w-full bg-[var(--to-surface)] border border-[var(--to-border)] rounded-lg px-3 py-2 font-mono text-[11px] text-[var(--to-text-primary)] resize-none focus:outline-none focus:border-[var(--to-long)]/60" rows={24} spellCheck={false} placeholder="Unavailable — no strategy loaded. Local draft only." /></div></div>;
}
